### ISSUE TITLE
Long press back freezes Flipper

### ISSUE THREAD

**Issue by ezod** [ezod/flipperzero-gps#12]
The new long press back to exit from #10 appears to lock up the Flipper, requiring a hard reset.

**Comment by ezod** [comment]
@xMasterX did you have this problem? I haven't had a chance to debug it, it's not obvious from looking at the code why this would occur.

**Comment by xMasterX** [comment]
> @xMasterX did you have this problem? I haven't had a chance to debug it, it's not obvious from looking at the code why this would occur.

No, all works fine for me

**Comment by ezod** [comment]
I was running `dev` firmware, switched back to official and it works fine. Closing.
