### ISSUE TITLE
Won't Load

### ISSUE THREAD

**Issue by aidenhyde** [ezod/flipperzero-gps#13]
I installed it using the fap builder. And it says api mismatch. Then it is just stuck on the hourglass loading screen. No updated.

**Comment by ezod** [comment]
That means the FAP was built for a different version of the firmware than is installed on your Flipper. What version of the firmware are you running?

Note you can obtain FAPs built for the latest `dev` and `release` channels right here on the GitHub page, instructions are in the README.

**Comment by aidenhyde** [comment]
Im running RM0523-2142-0.83.2-53a33f6

**Comment by ezod** [comment]
You'll need to build the FAP using the SDK for that firmware & version. You should be able to do that using [uFBT](https://github.com/flipperdevices/flipperzero-ufbt).
