### ISSUE TITLE
Question: Fake GPS receiver

### ISSUE THREAD

**Issue by iBobik** [ezod/flipperzero-gps#25]
I know it is out of scope for this project, but you maybe know some other project :-)

How to create device what will send GPS position messages (NMEA 0183) just like [external GPS receivers](https://www.garmin.com/en-US/p/645104) to the iOS devices?

Something for ESP32 or Flipper. User will hardcode fake latitude and longitude, pair (is pairing required) it with iPhone or iPad and map app will then think they are in this location.

**Comment by ezod** [comment]
You could construct NMEA 0183 sentences and send them over the USART easily enough, but based on your use case example I don't think this is what you are trying to do.

Instead it sounds like you are describing GPS spoofing. Aside from various other technical and legal issues, the Flipper Zero can't even transmit on the frequencies used by GPS signals.

**Comment by iBobik** [comment]
> You could construct NMEA 0183 sentences and send them over the USART easily enough, but based on your use case example I don't think this is what you are trying to do.
> 
> Instead it sounds like you are describing GPS spoofing. Aside from various other technical and legal issues, the Flipper Zero can't even transmit on the frequencies used by GPS signals.

No, I does not want to spoof GPS signal, but that Bluetooth messages what GPS receiver transmits to the iPad.

**Comment by ezod** [comment]
Oh, I didn't see the part about an external GPS receiver. I guess this would be a matter of making the Flipper mimic the Bluetooth device and then (probably) sending those NMEA 0183 sentences (you could maybe add sentence generation to [minmea](https://github.com/kosma/minmea) to handle that part). In any case, there's not much in this app that can help with that.
