### ISSUE TITLE
NEO-6M Not displaying in app

### ISSUE THREAD

**Issue by WA5RAT** [ezod/flipperzero-gps#9]
I have a NEO-6M connected as shown in the wiring diagram but I'm just getting all zeros in the app. I have verified it's working by using the UART Terminal app with 9600 baud rate set and I can see the NMEA sentences. I'll leave an example of one below

$GPGSV,3,3,09,29,74,325,39*64
$GPGLL,3118.44597,N,097 2156679,W,225424.00,A, A*7A

**Comment by krak3n77** [comment]
> I have a NEO-6M connected as shown in the wiring diagram but I'm just getting all zeros in the app. I have verified it's working by using the UART Terminal app with 9600 baud rate set and I can see the NMEA sentences. I'll leave an example of one below
> 
> $GPGSV,3,3,09,29,74,325,39_64 $GPGLL,3118.44597,N,097 2156679,W,225424.00,A, A_7A

Same issue, I ordered https://www.ebay.com/itm/204147071287

**Comment by ezod** [comment]
Do these modules not output RMC setences? @WA5RAT can you post a larger chunk of output? Everything I see online about these modules seems to show them sending RMC with latitude and longitude.

In any case, I've added support for GLL in 5b748296a30145b20237c3110accefb266268c99, maybe that will solve it if the RMC sentences aren't working.

Also let me know if you see the LED blinking at all (any colour), or if the last fix time is updating.

**Comment by ezod** [comment]
It also looks like someone thought it wasn't working in #8, but it was a matter of waiting for the module to get a fix. This can take quite a while from a cold start, particularly if you're inside a building.

**Comment by krak3n77** [comment]
> It also looks like someone thought it wasn't working in #8, but it was a matter of waiting for the module to get a fix. This can take quite a while from a cold start, particularly if you're inside a building.

I tried using the gps on the flipper and it didn't work, so I tried a gps to serial adapter and parsed the nmea, without moving the gps module. In my option it's not that it's not picking up gps signals.

**Comment by ezod** [comment]
@detectingdragon77 could you paste the NMEA output (a larger amount than above) please? I'm specifically looking for whether it contains RMC and/or GGA sentences.

**Comment by WA5RAT** [comment]
$GPVTG,,T,,M,0.173,N,0.321,K,A*26
$GPGGA,221858.00,3118.44821,N,09721.56175,W,1,05,1.80,223.5,M,-24.5,M,,*63
$GPGSA,A,3,05,29,18,15,20,,,,,,,,3.46,1.80,2.95*05
$GPGSV,2,1,07,05,44,036,29,11,14,087,15,13,43,093,22,15,55,147,26*75
$GPGSV,2,2,07,18,32,305,24,20,22,049,23,29,85,280,31*46
$GPGLL,3118.44821,N,09721.56175,W,221858.00,A,A*72
$GPRMC,221859.00,A,3118.44830,N,09721.56206,W,0.555,,230523,,,A*6D

I think that is all of different sentences. 
These are after it gets a lock and the led on the module starts flashing.
The last fix time does not update as just says 00:00:00 UTC as well as all other fields showing zero.
Led flashes blue after gps obtains lock as per gps module documentation.
I am on the version of the app that is installed by default on unleashed.  

But since it has the GGA and RMC sentences I've been stumped on what the issue could be.

**Comment by ezod** [comment]
The symptoms suggest it's simply not successfully parsing any NMEA sentences. The output looks good at a glance, and the module is 9600 baud, so I'm left thinking there might be some difference in the newline delimiter or similar that is stumping my admittedly hacky readline code. Do you know what's at the end of those lines? I'm splitting lines on `\n`.

I'll see if I can split that part from the UART code so it can be tested on the PC.

**Comment by WA5RAT** [comment]
There is actually nothing at the end of the lines so that may be the problem. That was a chuck copy and pasted straight from the Arduino serial monitor. It looks like the only thing separating the sentences is the $ at the beginning

**Comment by ezod** [comment]
If each sentence is on its own line like that, I assume they end with `\n` (wouldn't show other than the actual new line on the serial monitor).

**Comment by krak3n77** [comment]
> @detectingdragon77 could you paste the NMEA output (a larger amount than above) please? I'm specifically looking for whether it contains RMC and/or GGA sentences.


$GPRMC,032058.00,V,,,,,,,,,,N*71

$GPVTG,,,,,,,,,N*30

$GPGGA,032058.00,,,,,0,00,99.99,,,,,,*6A

$GPGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*30

$GPGSV,1,1,03,10,,,23,12,,,28,23,,,44*72

$GPGLL,,,,,032058.00,V,N*46

$GPRMC,032059.00,V,,,,,,,,,,N*70

$GPVTG,,,,,,,,,N*30

$GPGGA,032059.00,,,,,0,00,99.99,,,,,,*6B

$GPGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*30

$GPGSV,1,1,03,10,,,37,12,,,29,23,,,45*77

$GPGLL,,,,,032059.00,V,N*47

$GPRMC,032100.00,V,,,,,,,,,,N*7D

$GPVTG,,,,,,,,,N*30

$GPGGA,032100.00,,,,,0,00,99.99,,,,,,*66

$GPGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*30

$GPGSV,1,1,04,05,,,20,10,,,38,12,,,29,23,,,45*78

$GPGLL,,,,,032100.00,V,N*4A

$GPRMC,032101.00,V,,,,,,,,,,N*7C

$GPVTG,,,,,,,,,N*30

$GPGGA,032101.00,,,,,0,00,99.99,,,,,,*67

$GPGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*30

$GPGSV,1,1,03,10,,,37,12,,,29,23,,,45*77

$GPGLL,,,,,032101.00,V,N*4B

$GPRMC,032102.00,V,,,,,,,,,,N*7F

$GPVTG,,,,,,,,,N*30

$GPGGA,032102.00,,,,,0,00,99.99,,,,,,*64

$GPGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*30

$GPGSV,1,1,03,10,,,32,12,,,28,23,,,44*72

$GPGLL,,,,,032102.00,V,N*48

$GPRMC,032103.01,V,,,,,,,,,,N*7F

$GPVTG,,,,,,,,,N*30

$GPGGA,032103.01,,,,,0,00,99.99,,,,,,*64

$GPGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*30

$GPGSV,1,1,03,10,,,32,12,,,27,23,,,44*7D

$GPGLL,,,,,032103.01,V,N*48

$GPRMC,032104.00,V,,,,,,,,,,N*79

$GPVTG,,,,,,,,,N*30

$GPGGA,032104.00,,,,,0,00,99.99,,,,,,*62

$GPGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*30

$GPGSV,1,1,03,10,,,26,12,,,26,23,,,44*79

$GPGLL,,,,,032104.00,V,N*4E

**Comment by ezod** [comment]
These sentences seem to work fine when I spoof them to the Flipper using a FTDI cable, so it could be something to do with the line delimiter, the cadence of how the data is being sent, etc. that is not obvious from here. If someone wants to ship me a NEO-6M I'd be happy to debug it.

**Comment by WA5RAT** [comment]
I'll ship you one just send me an email with your shipping info

dylanbackus538@gmail.com

**Comment by ezod** [comment]
Sent, thanks.

**Comment by krak3n77** [comment]
I tried the gps app on the latest commit, it seems to work now that I am able to set the baud rate at 9600
